# Generated by Django 5.0.6 on 2024-06-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_products', '0001_initial'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundproduct',
            name='round_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rounds.round'),
            preserve_default=False,
        ),
    ]
