import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navigation />
        <main className='max-w-screen-xl p-4 xl:pt-8 m-auto'>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}

export default RootLayout