# Generated by Django 5.0.6 on 2024-06-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_type_id',
        ),
    ]
